.ruby: &ruby
  bundle_cache:
    folder: vendor/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script:
    - gem install bundler
    - bundle config set --local path 'vendor/bundle'
    - bundle update

remark_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: npm install
  remark_script: npm run remark

rubocop_task:
  <<: *ruby
  container:
    image: ruby:latest
  rubocop_script: bundle exec rubocop

test_task:
  depends_on:
    - remark
    - rubocop
  <<: *ruby
  container:
    matrix:
      image: ruby:2.6
      image: ruby:2.7
      image: ruby:3.0
  environment:
    CODECOV_TOKEN: ENCRYPTED[3693e59f74625639c3db63082c43ecd4924e64e2791d34d96c0317d3ee6637b7fd9b5c36b0a5ea402d5cac0b53331da3]
  test_script: bundle exec rspec
